# Generated by Django 3.1.7 on 2021-03-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
