# Generated by Django 3.1.7 on 2021-03-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210324_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='article',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
