# Generated by Django 3.1.7 on 2021-03-24 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210324_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstag',
            name='not_empty_filed',
            field=models.DateField(default=datetime.date(2021, 3, 24)),
        ),
    ]
