# Generated by Django 3.1.7 on 2021-03-29 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_goodstag_not_empty_filed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['draft', 'name', 'price'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='goodscategory',
            options={'ordering': ['draft', 'name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='goods',
            name='dt',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='is_sale',
        ),
        migrations.RemoveField(
            model_name='goodscategory',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='goodstag',
            name='not_empty_filed',
        ),
        migrations.AddField(
            model_name='goods',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='goods',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AddField(
            model_name='goods',
            name='image',
            field=models.ImageField(blank=True, upload_to='goods', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='goods',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodscategory',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AddField(
            model_name='goodscategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='article',
            field=models.CharField(default='', editable=False, max_length=10, verbose_name='Артикул'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.goodscategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='main.seller', verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='tags',
            field=models.ManyToManyField(related_name='goods', to='main.GoodsTag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='goodstag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
    ]
