# Generated by Django 3.1.7 on 2021-03-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210329_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodscategory',
            name='slug',
            field=models.SlugField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
