# Generated by Django 3.1.7 on 2021-03-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210330_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstag',
            name='slug',
            field=models.SlugField(default='none', editable=False, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodstag',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Название'),
        ),
    ]
